#!/usr/bin/env bash

# Explanation: Let us keep in $HOME/.config/startx empty files, if a file has the same name as the
# case indicated here, follow appropriate action for that file. I.e. If we have $HOME/.config/startx/xmodmap,
# then start xmodmap, otherwise do nothing for xmodmap.
if [[ -z "$DBUS_SESSION_BUS_ADDRESS" ]]; then
      eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

if [[ -d $HOME/.config/startx ]]; then
    for arguments in $(find $HOME/.config/X11/load/ -type f)
    do
        case $arguments in
            *bell) # Turn the bell off
                xset -b
                shift ;;
            *fonts)
                xset +dpms +fp /usr/share/fonts/local,/usr/share/fonts/artwiz-fonts
                shift ;;
            *gkeyring)
                # source /etc/X11/xinit/xinitrc.d/30-dbus
                eval $(/usr/bin/gnome-keyring-daemon --start)
                export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK SSH_AGENT_PID
                shift ;;
            *trayer)
                sleep 10s && trayer --edge top --align right \
                    --widthtype request --expand true --height 12 \
                    --transparent true --alpha 0 --tint 0x1A1918 &
                shift ;;
            *nm-applet)
                sleep 10s && nm-applet &
                shift ;;
            *udiskie) # Let's start udiskie (udisks wrapper)
                udiskie --use-udisks2 --no-tray &
                shift ;;
            *xmodmap) # Start custom bind of keys
                xmodmap $HOME/.config/xmodmap
                shift ;;
            *xresources) # Start custom settings for urxvt
                xrdb -merge ~/.config/Xresources
                shift ;;
        esac
    done
fi

# Let's set a pointer
xsetroot -cursor_name left_ptr

# Use $XDG_RUNTIME_DIR for some folders
mkdir -p $XDG_RUNTIME_DIR/{adobe,macromedia}
ln -sfn $XDG_RUNTIME_DIR/adobe ~/.adobe
ln -sfn $XDG_RUNTIME_DIR/macromedia ~/.macromedia

# Which WM/DE to launch
# exec xmonad
exec i3
# exec openbox-session
# exec startxfce4
