#!/usr/bin/env bash

dotfiles_path=$(dirname "$0")

# Do not proceed if stow is not installed
if [[ ! -x /usr/bin/stow ]] || [[ ! -x /bin/stow ]]; then
    echo "This script needs stow, please install it with your package manager of preference"
    exit


# If stow is installed, then proceed with the following:
elif [[ $1 == "--deploy" ]] && [[ $2 == "popular" ]]; then
    stow -v cower git newsbeuter termite unclassified vim X xmonad youtube zsh

elif [[ $1 == "--conclude" ]] && [[ $2 == "popular" ]]; then
    stow -v --delete cower git newsbeuter termite unclassified vim X xmonad youtube zsh

# What to do for when we want to deploy vim
elif [[ $1 == "--vim" ]]; then
    mkdir -p "$dotfiles_path"/vim/.vim/{autoload,bundle,backup,swap}
    git clone git://github.com/tpope/vim-pathogen.git "$dotfiles_path"/vim/.vim/bundle/pathogen
    git clone git://github.com/tpope/vim-commentary.git "$dotfiles_path"/vim/.vim/bundle/vim-commentary
    git clone git://github.com/SirVer/ultisnips.git "$dotfiles_path"/vim/.vim/bundle/ultisnips
    git clone git://github.com/scrooloose/nerdtree.git "$dotfiles_path"/vim/.vim/bundle/nerdtree
    git clone git://github.com/mattn/gist-vim "$dotfiles_path"/vim/.vim/bundle/gist-vim
    git clone git://github.com/mattn/webapi-vim "$dotfiles_path"/vim/.vim/bundle/webapi-vim
    git clone git://github.com/godlygeek/tabular.git "$dotfiles_path"/vim/.vim/bundle/tabular
    git clone https://github.com/xuhdev/SingleCompile.git "$dotfiles_path"/vim/.vim/bundle/single-compile
    echo "Done clonning the plugins, now let us create the symlinks"
    stow -v vim

else
    echo "The only two valig arguments at the moment are:"
    echo -e "\t--deploy popular (A basic alias for 'stow -v cower...etc')"
    echo -e "\t--conclude popular (A basic alias for 'stow -v --delete cower...etc')"
    echo -e "\t--vim (For creating the necessary folders, installation of plugins, and symlinking)"
fi
