#!/usr/bin/env bash

dotfiles_path=$(dirname "$0")

# Do not proceed if stow is not installed
if [[ ! -x /usr/bin/stow ]] || [[ ! -x /bin/stow ]]; then
    echo "This script needs stow, please install it with your package manager of preference"
    exit


# If stow is installed, then proceed with the following:
elif [[ $1 == "--deploy" ]] && [[ $2 == "popular" ]]; then
    stow -v cower git newsbeuter termite unclassified vim X X-xinitrc xmonad youtube zsh

elif [[ $1 == "--conclude" ]] && [[ $2 == "popular" ]]; then
    stow -v --delete cower git newsbeuter termite unclassified vim X X-xinitrc xmonad youtube zsh

# What to do for when we want to deploy vim
elif [[ $1 == "--vim" ]]; then
    mkdir -p "$dotfiles_path"/vim/.vim/{autoload,bundle,backup,swap}
    git submodule init
    git submodule update
    stow -v vim

# What to do for when we want to deploy xmonad
elif [[ $1 == "--xmonad" ]]; then
    if [[ ! -x /usr/bin/cabal ]] && [[ ! -x /usr/bin/ghc ]]; then
        echo "This option needs cabal and ghc to be installed. Try doing that first"
        exit
    fi
    cabal update && cabal install xmonad && cabal install xmonad-contrib
    echo "You also need to add \$HOME/.cabal/bin to your \$PATH. Or deploy zsh"
    echo "Which already has \$PATH configured appropriately."

# Display the help
else
    echo "The only two valig arguments at the moment are:"
    echo -e "\t--deploy popular (A basic alias for 'stow -v cower...etc')"
    echo -e "\t--conclude popular (A basic alias for 'stow -v --delete cower...etc')"
    echo -e "\t--vim (For creating the necessary folders, installation of plugins, and symlinking)"
fi
