#!/bin/bash

# This script outputs how much data I have received and transmitted since the interface
# was brought up. Output looks like:
# eth0:<fc=#5d7caf> 7508 </fc>MiB<fc=#FBA4A8> 334 </fc>MiB
# xmobar replaces those color codes, so 7508 would look blue and 334 red. The first set
# of digits shows us how much we have downloaded (7508MiB in our example), and the second
# set of digits shows how much we have uploaded (334MiB in our example)

shopt -s extglob
net_interfaces=(/sys/class/net/!(lo))

for i in $net_interfaces; do
    received=$(cat $i/statistics/rx_bytes)
    transferred=$(cat $i/statistics/tx_bytes)

    # Check if we have the icons folder. If we have the folder, add the icons to our output.
    # If the folder does not exist, then do not add icons to our output.
    if [[ -d $HOME/.config/icons ]]; then
        # The ${i##*/} is for substring removal.
        # I.e. eth0 instead of /sys/class/net/eth0
        # echo -n "${i##*/}:<fc=#5d7caf> <icon=.config/icons/net_down.xbm/> $(($received/1024/1024)) </fc>MiB"
        echo -n "<fc=#5d7caf> <icon=.config/icons/net_down.xbm/> $(($received/1024/1024)) </fc>MiB"
        echo "<fc=#FBA4A8> <icon=.config/icons/net_up.xbm/> $(($transferred/1024/1024)) </fc>MiB"
    else
        # The ${i##*/} is for substring removal.
        # I.e. eth0 instead of /sys/class/net/eth0
        # echo -n "${i##*/}:<fc=#5d7caf> $(($received/1024/1024)) </fc>MiB"
        echo -n "<fc=#5d7caf> $(($received/1024/1024)) </fc>MiB"
        echo "<fc=#FBA4A8> $(($transferred/1024/1024)) </fc>MiB"
    fi
done
