set guifont=DejaVu\ Sans\ Mono\ 11
"m remove menu bar
"r remove right-hand scrollbar
"L remove left-hand scrollbar
"T remove toolbar
" set guioptions=agpi
set guioptions-=mrL
aunmenu ToolBar.Help
aunmenu ToolBar.FindHelp
aunmenu ToolBar.RunScript
aunmenu ToolBar.Print

set guicursor=a:blinkon0
set mousef

set lines=40
set columns=90

set mouses=i-r:beam,s:updown,sd:udsizing,vs:leftright,vd:lrsizing,m:no,ml:up-arrow,v:rightup-arrow
set mousehide
