#!/usr/bin/env bash

# Establish initial session
tmux new -s Main -d -s0 -nbot 'exec bash $HOME/bot.sh' #screen 0:1
tmux neww -d -nsyslog 'exec journalctl -afn100' #screen 0:2
tmux neww -d -nsshd 'exec journalctl -afn100 /usr/bin/sshd' #screen 0:3
